# Generated by Django 5.1.6 on 2025-03-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('teacher_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='teacher_id')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('mobile_number', models.CharField(max_length=10, verbose_name='mobile_number')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('specialization', models.CharField(max_length=255, verbose_name='specialization')),
            ],
        ),
    ]
