# Generated by Django 5.1.6 on 2025-03-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(max_length=255, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='mobile_number'),
        ),
    ]
