# Generated by Django 5.1.6 on 2025-03-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_teacherprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='password',
            field=models.CharField(default='iron@man-power+', max_length=50, verbose_name='password'),
        ),
    ]
