# Generated by Django 5.1.6 on 2025-03-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Result',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('stu_roll_no', models.IntegerField(default=0, unique=True)),
        #         ('stu_class', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1)),
        #         ('marks', models.IntegerField(default=0)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='StudentProfile',
        #     fields=[
        #         ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='student_id')),
        #         ('name', models.CharField(max_length=70)),
        #         ('email', models.EmailField(default='example@gmail.com', max_length=255, unique=True)),
        #         ('password', models.CharField(default='iron@man-power+', max_length=50, verbose_name='password')),
        #         ('city', models.CharField(default='junagadh', max_length=70)),
        #         ('roll_no', models.IntegerField(default=0, unique=True)),
        #         ('stu_class', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], default=1)),
        #     ],
        # ),
    ]
