# Generated by Django 5.1.6 on 2025-03-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Junagadh', max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
