# Generated by Django 5.1.6 on 2025-03-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_stu_class_result_student_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='password',
            field=models.CharField(default='iron@man-power+', max_length=255, verbose_name='password'),
        ),
    ]
