# Generated by Django 5.1.6 on 2025-03-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_result_profile_stu_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password',
            field=models.CharField(default='iron@man-power+', max_length=50, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='junagadh', max_length=70),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(auto_created=True, default=0, unique=True),
        ),
    ]
