# Generated by Django 5.1.6 on 2025-03-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_profile_password_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roll_no',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
