# Generated by Django 5.1.6 on 2025-03-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_class', models.CharField(max_length=255, verbose_name='user_class')),
                ('user_id', models.CharField(max_length=180, verbose_name='user_id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('seen', models.BooleanField(default=False, verbose_name='seen')),
            ],
        ),
    ]
