# Generated by Django 5.1.6 on 2025-03-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='course_id')),
                ('course_name', models.CharField(max_length=255, verbose_name='course_name')),
                ('stu_class', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='stu_class')),
            ],
        ),
    ]
